package aaron.cheng.mybatis.dao.kidodata;

import aaron.cheng.mybatis.entry.ChildHomeSchool;

public interface ChildHomeSchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_home_school
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    int deleteByPrimaryKey(Integer childid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_home_school
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    int insert(ChildHomeSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_home_school
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    int insertSelective(ChildHomeSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_home_school
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    ChildHomeSchool selectByPrimaryKey(Integer childid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_home_school
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    int updateByPrimaryKeySelective(ChildHomeSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_home_school
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    int updateByPrimaryKey(ChildHomeSchool record);
}