package aaron.cheng.mybatis.entry;

import java.util.Date;

public class ChildHomeSchool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_home_school.ChildId
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    private Integer childid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_home_school.HomeLat
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    private String homelat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_home_school.HomeLng
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    private String homelng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_home_school.HomeUpdate
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    private Date homeupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_home_school.SchoolLat
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    private String schoollat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_home_school.SchoolLng
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    private String schoollng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_home_school.SchoolUpdate
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    private Date schoolupdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_home_school.ChildId
     *
     * @return the value of child_home_school.ChildId
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public Integer getChildid() {
        return childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_home_school.ChildId
     *
     * @param childid the value for child_home_school.ChildId
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public void setChildid(Integer childid) {
        this.childid = childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_home_school.HomeLat
     *
     * @return the value of child_home_school.HomeLat
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public String getHomelat() {
        return homelat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_home_school.HomeLat
     *
     * @param homelat the value for child_home_school.HomeLat
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public void setHomelat(String homelat) {
        this.homelat = homelat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_home_school.HomeLng
     *
     * @return the value of child_home_school.HomeLng
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public String getHomelng() {
        return homelng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_home_school.HomeLng
     *
     * @param homelng the value for child_home_school.HomeLng
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public void setHomelng(String homelng) {
        this.homelng = homelng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_home_school.HomeUpdate
     *
     * @return the value of child_home_school.HomeUpdate
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public Date getHomeupdate() {
        return homeupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_home_school.HomeUpdate
     *
     * @param homeupdate the value for child_home_school.HomeUpdate
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public void setHomeupdate(Date homeupdate) {
        this.homeupdate = homeupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_home_school.SchoolLat
     *
     * @return the value of child_home_school.SchoolLat
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public String getSchoollat() {
        return schoollat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_home_school.SchoolLat
     *
     * @param schoollat the value for child_home_school.SchoolLat
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public void setSchoollat(String schoollat) {
        this.schoollat = schoollat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_home_school.SchoolLng
     *
     * @return the value of child_home_school.SchoolLng
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public String getSchoollng() {
        return schoollng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_home_school.SchoolLng
     *
     * @param schoollng the value for child_home_school.SchoolLng
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public void setSchoollng(String schoollng) {
        this.schoollng = schoollng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_home_school.SchoolUpdate
     *
     * @return the value of child_home_school.SchoolUpdate
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public Date getSchoolupdate() {
        return schoolupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_home_school.SchoolUpdate
     *
     * @param schoolupdate the value for child_home_school.SchoolUpdate
     *
     * @mbg.generated Fri Oct 19 16:17:36 CST 2018
     */
    public void setSchoolupdate(Date schoolupdate) {
        this.schoolupdate = schoolupdate;
    }
}