package aaron.cheng.mybatis.entry;

import java.util.Date;

public class ChildWifi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_wifi.Id
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_wifi.ChildId
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    private Integer childid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_wifi.WiFiName
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    private String wifiname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_wifi.WiFiPwd
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    private String wifipwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_wifi.WiFiState
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    private Short wifistate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_wifi.CreateTime
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column child_wifi.OperationType
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    private Integer operationtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_wifi.Id
     *
     * @return the value of child_wifi.Id
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_wifi.Id
     *
     * @param id the value for child_wifi.Id
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_wifi.ChildId
     *
     * @return the value of child_wifi.ChildId
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public Integer getChildid() {
        return childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_wifi.ChildId
     *
     * @param childid the value for child_wifi.ChildId
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public void setChildid(Integer childid) {
        this.childid = childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_wifi.WiFiName
     *
     * @return the value of child_wifi.WiFiName
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public String getWifiname() {
        return wifiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_wifi.WiFiName
     *
     * @param wifiname the value for child_wifi.WiFiName
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public void setWifiname(String wifiname) {
        this.wifiname = wifiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_wifi.WiFiPwd
     *
     * @return the value of child_wifi.WiFiPwd
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public String getWifipwd() {
        return wifipwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_wifi.WiFiPwd
     *
     * @param wifipwd the value for child_wifi.WiFiPwd
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public void setWifipwd(String wifipwd) {
        this.wifipwd = wifipwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_wifi.WiFiState
     *
     * @return the value of child_wifi.WiFiState
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public Short getWifistate() {
        return wifistate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_wifi.WiFiState
     *
     * @param wifistate the value for child_wifi.WiFiState
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public void setWifistate(Short wifistate) {
        this.wifistate = wifistate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_wifi.CreateTime
     *
     * @return the value of child_wifi.CreateTime
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_wifi.CreateTime
     *
     * @param createtime the value for child_wifi.CreateTime
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column child_wifi.OperationType
     *
     * @return the value of child_wifi.OperationType
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public Integer getOperationtype() {
        return operationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column child_wifi.OperationType
     *
     * @param operationtype the value for child_wifi.OperationType
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    public void setOperationtype(Integer operationtype) {
        this.operationtype = operationtype;
    }
}