package aaron.cheng.mybatis.dao.kidostatistics;

import aaron.cheng.mybatis.entry.ChildWifi;

public interface ChildWifiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_wifi
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    int insert(ChildWifi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table child_wifi
     *
     * @mbg.generated Fri Oct 19 15:35:27 CST 2018
     */
    int insertSelective(ChildWifi record);
}